### ISSUE TITLE
Plugin approval

### ISSUE THREAD

**Issue by NyakudyaA** [parmendel/spatialanalysistoolbox#1]
# Problem

Can you please add the dependencies of the plugin in https://github.com/parmendel/spatialanalysistoolbox/blob/main/metadata.txt#L40

@parmendel

**Comment by parmendel** [comment]
Hello, I added the dependencies in metadata.txt

**Comment by parmendel** [comment]
Hello, I added the dependencies in metadata.txt

Thank you.

Στις Πέμ 3 Μαρ 2022 στις 8:20 π.μ., ο/η mazano ***@***.***>
έγραψε:
