### ISSUE TITLE
Import "skp" error.

### ISSUE THREAD

**Issue by felipedantas-pi** [parmendel/spatialanalysistoolbox#2]
I'm using a computer with Windows10, win64 and QGIS version 3.24.

![qgis-bin_eAlKUJZmI7](https://user-images.githubusercontent.com/69129407/157728130-f9e7efad-eea4-42f1-a8da-2403833c0928.png)

I installed the dependencies in OSGeo4w Shell, but this error is appearing for me.
![qgis-bin_s8kS73HSkZ](https://user-images.githubusercontent.com/69129407/157728174-cd80e99a-5574-468f-b26d-fbc51f3832b8.png)

**Comment by parmendel** [comment]
Hello, first of all you need to upgrade to v0.2, if you haven't already. In this version you need to install (pip install libpysal esda mgwr).

If this doesn't work, installing sklearn (pip install -U scikit-learn) as it seems "skp" in esda/silouettes.py is short for sklearn.metrics.pairwise.

**Comment by felipedantas-pi** [comment]
Hi,

I already have all the dependencies installed and the plugin updated to version 0.2.
![cmd_oZgWX1TnGN](https://user-images.githubusercontent.com/69129407/157933588-93f1830c-316b-4188-8cd0-2a4b9f445085.png)

**Comment by parmendel** [comment]
Hello, I installed the same QGIS version on a windows VM but I couldn't reproduce your issue. Everything worked normally.

Look for pairwise.py in sklearn (<python_libs>/sklearn/metrics/pairwise.py). If it is missing add it and add the lines below in __init.py__ of the same folder.
[pairwise.zip](https://github.com/parmendel/spatialanalysistoolbox/files/8239337/pairwise.zip)

from .pairwise import euclidean_distances
from .pairwise import nan_euclidean_distances
from .pairwise import pairwise_distances

from .pairwise import pairwise_distances_argmin
from .pairwise import pairwise_distances_argmin_min
from .pairwise import pairwise_kernels
from .pairwise import pairwise_distances_chunked

If this doesn't work try disabling silhouettes.py by commenting line 
"from .silhouettes import path_silhouette, boundary_silhouette" in <python_libs>/esda/__init__.py
