### ISSUE TITLE
Unable to use plugin

### ISSUE THREAD

**Issue by NicholasDeKock** [parmendel/spatialanalysistoolbox#3]
When I have downloaded the plugin and try to install, this window comes up and it keeps loading besides the fact that I have installed all the dependancies in the OSGeo shell. Is there perhaps a workaround?
![image](https://user-images.githubusercontent.com/50359577/162809273-f40ca52b-6766-4ca2-ab76-a34678c91fbb.png)

**Comment by parmendel** [comment]
I haven't came across this window when I was testing the dependencies. Can you tell me the QGIS version and your OS?
Try importing the libraries in QGIS Python console to see if there are installed in the environment QGIS uses.
(import pandas geopandas etc..)

I'll try on a virtual machine to check if there's a workaround.

**Comment by NicholasDeKock** [comment]
Interestingly, I cannot reproduce that error now. However I am presented with the following:
![image](https://user-images.githubusercontent.com/50359577/163148384-89500b1d-438f-46d9-a231-53af5cb9d6a8.png)

**Comment by parmendel** [comment]
I did a fresh installation and the Plugin Dependencies Manager window, as you said, appeared only once.
Then I get the second error you got. I think for some reason it tries to install the dependencies again.

After some testing, I had it working by removing the dependecies from plugin's metadata
From QGIS go to Setting->User profiles->Open active profile folder
From the new file explorer window go to Python->plugins->spatialanalysistoolbox->metadata.txt
In metadata search for plugin_dependencies and remove the dependencies after =
Finally, restart QGIS and try enabling again the plugin.

**Comment by NicholasDeKock** [comment]
Apologies for not getting back sooner - I followed your solution and it works. Thanks very much for your assistance!
