### ISSUE TITLE
error during installation of spatial analysis toolbox

### ISSUE THREAD

**Issue by cedric1960** [parmendel/spatialanalysistoolbox#6]
i have been trying to install the "spatial analysis toolbox" plugin in qgis but it's shows that there is an error. 
the Screenshot Bellow shows the error. can someone help me solve this problem???
![ERROR](https://github.com/parmendel/spatialanalysistoolbox/assets/133085835/8f7f001f-9b22-4a25-9a24-8b750caea882)

**Comment by rodreras** [comment]
Open OSGeo4W shell and then write `pip install geopandas`. Close QGIS and re-open. This probably solves the issue.

**Comment by cedric1960** [comment]
Thanks very much I tried it and the plugin was installed successfully

**Comment by cedric1960** [comment]
Good morning to everyone
Can someone help me with this problem,
I have installed R in qgis but each time I run any of the algorithm I can not view the final result. I have tried everything but to no avail. Please I meet your help
